### ISSUE TITLE
Цвета hover

### ISSUE THREAD

**Issue by olehkrupko** [PI-13-5/BistroDriveWebApp#65]
Так выглядит не выделенное
<img width="156" alt="2015-12-10 15 57 56" src="https://cloud.githubusercontent.com/assets/9454226/11717091/d47dd604-9f56-11e5-9328-dc4186129574.png">
А так — выделенное
<img width="213" alt="2015-12-10 14 04 43" src="https://cloud.githubusercontent.com/assets/9454226/11717103/e17f3956-9f56-11e5-8515-aaed8b04bbb5.png">

**Comment by yakovenkodenis** [comment]
исправил.
